#ifndef __LED_H
#define __LED_H
#include "mymain.h"

#define LED1_IS_AVAILABLE 1
#define LED2_IS_AVAILABLE 1
#define LED3_IS_AVAILABLE 0

#if LED1_IS_AVAILABLE
#define LED1_GPIO_PORT GPIOB
#define LED1_GPIO_PIN  GPIO_PIN_2
#define LED1_TOGGLE() HAL_GPIO_TogglePin(LED1_GPIO_PORT, LED1_GPIO_PIN)
#define LED1_ON()     HAL_GPIO_WritePin(LED1_GPIO_PORT, LED1_GPIO_PIN, RESET)
#define LED1_OFF()     HAL_GPIO_WritePin(LED1_GPIO_PORT, LED1_GPIO_PIN, SET)
#endif


#if LED2_IS_AVAILABLE
#define LED2_GPIO_PORT GPIOC
#define LED2_GPIO_PIN  GPIO_PIN_5
#define LED2_TOGGLE() HAL_GPIO_TogglePin(LED2_GPIO_PORT, LED2_GPIO_PIN)
#endif

#if LED3_IS_AVAILABLE
#define LED3_GPIO_PORT GPIOB
#define LED3_GPIO_PIN  GPIO_PIN_11
#define LED3_TOGGLE() HAL_GPIO_TogglePin(LED3_GPIO_PORT, LED3_GPIO_PIN)
#endif

#endif // ! __LED_H
